CXX = g++
CXXFLAGS = -std=c++17 -Wall
TARGET = inventory_management_system
OBJECTS = main.o Product.o Supplier.o Organization.o

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

clean:
	rm -f $(TARGET) *.o
